- name: configure the catalouge server
  hosts: catalouge
  become: yes
  tasks:
    - name: disable the nodejs module
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enable the nodejs module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
      
    - name: create directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download the application file
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: unzip the downloaded zip file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        


        