- name: configure the catalogue server
  hosts: catalogue
  become: yes
  tasks:
    - name: disable the nodejs module
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enable the nodejs module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
      
    - name: create directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download the application file
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

# here this module thinks the file already existed in ansible server, why becasue we are executing this yaml code in ansible server, so it thinks like that and it thinks that file needs to extract on remote server(catalouge server)
    - name: unzip the downloaded zip file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes #it will tell that file already existed in catalogue server. If we wont't give this, then we will get error.
    - name: install npm packages
      community.general.npm:
        path: /app

    - name: copy the catalgue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: reload the systemctl demon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and ebale the service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: copy the mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install the mongodb server
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check produscts loaded or not from mongodb
      ansible.builtin.command: mongosh --host mongodb.kotadurgagangumalla.fun --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalouge_output

    - name: print the catalogue output
      ansible.builtin.debug:
        msg: "{{catalogue_output}}"

    - name: load the data
      ansible.builtin.shell:  mongosh --host mongodb.kotadurgagangumalla.fun </app/db/master-data.js &>>$LOG_FILE
      when: catalogue_output.stdout | int < 0
    



        