- name: configure the dispatch service
  hosts: dispatch
  become: yes
  tasks:
  - name: install the golang
    ansible.builtin.dnf:
      name: golang
      state: installed

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: yes
      home: /app

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the data
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip

  - name: unzip the download the zip file
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: true
      

