- name: configure the user service
  hosts: user
  become: yes
  tasks:
  - name: disable the current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable the nodejs:20 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install the nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: user name add as roboshop
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create /app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download the zip file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
# I catalogue what we said same thing will happen here. That's why we give the resource_src as yes
  - name: unzip the downloaded file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: insall npm in /app
    community.general.npm:
      name: npm
      path: /app

  - name: reload the demon service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable service
    ansible.builtin.service:
      name: user
      state: started
      status: enabled

